---
# ====== Application: Modernization ==========================
identification: 
  name: Modernization
  alias: MODERNIZATION
  version: Release 1.0

row-search: 
  tokenize: true
  text-query-function: None

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification

report-printing: 
  type: Use Instance Settings

advanced: 
  friendly-urls: true
  allow-feedback: true
  logging: true
  debugging: true
  compatibility-mode: 24.2
  accessible-read-only-items: true
  pass-ecid: Y

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: Oracle APEX Accounts # 23121809532236357974

authorization: 
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Disabled

session-state-protection: 
  enabled: true

security: 
  deep-linking: Disabled
  browser-cache: Disabled
  embed-in-frames: Deny
  referrer-policy: strict-origin
  html-escaping-mode: Extended

database-session: 
  parsing-schema: WKSP_GRAPHTREK

globalization: 
  primary-language: English (en)
  document-direction: Language Default
  language-derived-from: Application Primary Language
  automatic-time-zone: false
  automatic-csv-encoding: true

application-format-masks: 
  date: DS
  timestamp: DS
  timestamp-time-zone: DS

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Text
  text: Modernization

progressive-web-app: 
  enable: true
  installable: true
  display: Standalone
  screen-orientation: Any
  ios-status-bar-style: Default
  enable-push-notifications: false

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:1:&APP_SESSION.::&DEBUG.:::'
    page: 1 # Home

  login-url: 
    url: 'f?p=&APP_ID.:LOGIN:&APP_SESSION.::&DEBUG.:::'
    page: LOGIN

navigation-menu: 
  list-template: Side Navigation Menu
  template-options: 
  - '#DEFAULT#'
  - t-TreeNav--styleA
  - js-navCollapsed--hidden
  list-position: Side
  list: Navigation Menu # 23121810397503357975

navigation-bar: 
  implementation: List
  list: Navigation Bar # 23121811578449357978
  list-template: Navigation Bar
  template-options: 
  - '#DEFAULT#'

javascript: 
  include-jquery-migrate: false

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: false
  add-"built-with-apex"-to-footer: false
  auto-dismiss-success-messages: false

subscription: 
  version-number: 15614477176396

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 1
  identification: 
    name: APP_NAME

  value: 
    static-value: Modernization

component-settings: 
- # ====== Component Setting: NATIVE_OPEN_AI_ASSISTANT =========
  id: 23121805024491357970
  identification: 
    name: NATIVE_OPEN_AI_ASSISTANT
    type: Dynamic Action

  subscription: 
    version-number: 15614305886700

- # ====== Component Setting: NATIVE_COLOR_PICKER ==============
  id: 23121805389051357971
  identification: 
    name: NATIVE_COLOR_PICKER
    type: Item

  subscription: 
    version-number: 15614305886703

- # ====== Component Setting: NATIVE_DATE_PICKER_APEX ==========
  id: 23121805695485357972
  identification: 
    name: NATIVE_DATE_PICKER_APEX
    type: Item

  subscription: 
    version-number: 15614305886703

- # ====== Component Setting: NATIVE_GEOCODED_ADDRESS ==========
  id: 23121805919061357972
  identification: 
    name: NATIVE_GEOCODED_ADDRESS
    type: Item

  subscription: 
    version-number: 15614305886703

- # ====== Component Setting: NATIVE_SELECT_MANY ===============
  id: 23121806210349357972
  identification: 
    name: NATIVE_SELECT_MANY
    type: Item

  subscription: 
    version-number: 15614305886703

- # ====== Component Setting: NATIVE_SINGLE_CHECKBOX ===========
  id: 23121806528406357972
  identification: 
    name: NATIVE_SINGLE_CHECKBOX
    type: Item

  subscription: 
    version-number: 15614305886703

- # ====== Component Setting: NATIVE_STAR_RATING ===============
  id: 23121806890901357972
  identification: 
    name: NATIVE_STAR_RATING
    type: Item

  subscription: 
    version-number: 15614305886704

- # ====== Component Setting: NATIVE_YES_NO ====================
  id: 23121807193768357972
  identification: 
    name: NATIVE_YES_NO
    type: Item

  subscription: 
    version-number: 15614305886704

- # ====== Component Setting: NATIVE_GEOCODING =================
  id: 23121807463105357973
  identification: 
    name: NATIVE_GEOCODING
    type: Process

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER

  subscription: 
    version-number: 15614305886704

- # ====== Component Setting: NATIVE_DISPLAY_SELECTOR ==========
  id: 23121807798433357973
  identification: 
    name: NATIVE_DISPLAY_SELECTOR
    type: Region

  subscription: 
    version-number: 15614305886704

- # ====== Component Setting: NATIVE_IR ========================
  id: 23121808034919357973
  identification: 
    name: NATIVE_IR
    type: Region

  subscription: 
    version-number: 15614305886704

- # ====== Component Setting: NATIVE_MAP_REGION ================
  id: 23121808383592357974
  identification: 
    name: NATIVE_MAP_REGION
    type: Region

  subscription: 
    version-number: 15614305886708

- # ====== Component Setting: NATIVE_ADFBC =====================
  id: 23121808692979357974
  identification: 
    name: NATIVE_ADFBC
    type: REST Data Source

  subscription: 
    version-number: 15614305886709

- # ====== Component Setting: NATIVE_BOSS ======================
  id: 23121808932242357974
  identification: 
    name: NATIVE_BOSS
    type: REST Data Source

  subscription: 
    version-number: 15614305886710

