name: Build and Push to GHCR

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Kódbázis klónozása
        uses: actions/checkout@v4

      - name: Feltöltés GitHub Artifacts-ba
        uses: actions/upload-artifact@v4
        with:
          name: apex-modernization
          path: apex-modernization_latest.tar

#     - name: Docker image mentése artifaktként
#        uses: actions/upload-artifact@v4
#        with:
#          name: virtualthreaddemo-image
#          path: |
#            $(docker save ghcr.io/${{ github.actor }}/virtualthreaddemo:latest -o virtualthreaddemo_latest.tar)
#            virtualthreaddemo_latest.tar